[package]
name = "pydrology-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pydrology-core.workspace = true
pyo3.workspace = true
numpy.workspace = true
